# Generated by Django 5.2.3 on 2025-09-21 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contant_messages',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='پاسخ مدیر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='ایمیل')),
                ('order_text', models.TextField(verbose_name='متن صفارش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='نام محصول')),
                ('description', models.TextField(null=True, verbose_name='توضیحات')),
                ('available', models.CharField(max_length=255, null=True, verbose_name='موجودی')),
                ('price', models.CharField(max_length=100, null=True, verbose_name='قیمت')),
                ('image_url', models.CharField(blank=True, max_length=255, verbose_name='آدرس عکس')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_images/')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعّال')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='WorkSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='عکس نمونه کار را آپلود کنید.', upload_to='work_samples/%Y/%m/%d/', verbose_name='عکس')),
                ('description', models.CharField(blank=True, help_text='توضیحات کوتاه برای نمونه کار (اختیاری).', max_length=255, verbose_name='توضیحات')),
                ('product', models.ForeignKey(help_text='این نمونه کار مربوط به کدام محصول است؟', on_delete=django.db.models.deletion.CASCADE, related_name='work_samples', to='store.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': 'نمونه کارها',
            },
        ),
    ]
