# Generated by Django 5.2.3 on 2025-09-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'دسته بندی محصول', 'verbose_name_plural': 'دسته\u200cبندی\u200cها محصول'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'سفارش ثبت شده', 'verbose_name_plural': 'سفارشات ثبت شده'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'سوالات متداول', 'verbose_name_plural': 'سوالات متداول'},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='درخاست ثبت سفارش'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='متن صفارش'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='شماره تماس'),
        ),
    ]
