# Generated by Django 5.2.3 on 2025-09-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_delete_order_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'سفارش ثبت شده', 'verbose_name_plural': 'سفارشات ثبت شده'},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='متن سفارش'),
        ),
        migrations.AlterModelTable(
            name='contactmessage',
            table=None,
        ),
    ]
