# Generated by Django 5.2.3 on 2025-09-27 11:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='category',
            name='content',
            field=ckeditor.fields.RichTextField(default='', verbose_name='محتوای توضیحات'),
            preserve_default=False,
        ),
    ]
