# Generated by Django 5.1.7 on 2025-08-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "contant_messages",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                ("message", models.TextField(verbose_name="متن پیام")),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="تأیید شده"),
                ),
                (
                    "answer",
                    models.TextField(blank=True, null=True, verbose_name="پاسخ مدیر"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام و نام خانوادگی"),
                ),
                ("phone", models.CharField(max_length=15, verbose_name="شماره تماس")),
                (
                    "product_name",
                    models.CharField(max_length=100, verbose_name="نام محصول"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="تعداد")),
                ("address", models.TextField(verbose_name="آدرس")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_fa",
                    models.CharField(
                        max_length=100, null=True, verbose_name="نام محصول (فارسی)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Product Name (English)",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="اسم المنتج (العربية)",
                    ),
                ),
                (
                    "description_fa",
                    models.TextField(null=True, verbose_name="توضیحات (فارسی)"),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description (English)"
                    ),
                ),
                (
                    "description_ar",
                    models.TextField(
                        blank=True, null=True, verbose_name="الوصف (العربية)"
                    ),
                ),
                (
                    "available_fa",
                    models.CharField(
                        max_length=255, null=True, verbose_name="موجودی (فارسی)"
                    ),
                ),
                (
                    "available_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Availability (En)",
                    ),
                ),
                (
                    "available_ar",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="التوفر (Ar)",
                    ),
                ),
                (
                    "category_fa",
                    models.CharField(
                        max_length=50, null=True, verbose_name="دسته\u200cبندی (فارسی)"
                    ),
                ),
                (
                    "category_en",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Category (English)",
                    ),
                ),
                (
                    "category_ar",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="فئة (العربية)",
                    ),
                ),
                (
                    "price_fa",
                    models.CharField(
                        max_length=100, null=True, verbose_name="قیمت (فارسی)"
                    ),
                ),
                (
                    "price_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Price (English)",
                    ),
                ),
                (
                    "price_ar",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="السعر (العربية)",
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="آدرس عکس"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="products_images/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعّال")),
            ],
        ),
    ]
