# Generated by Django 5.2.3 on 2025-09-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان نماد')),
                ('image', models.ImageField(upload_to='trust_symbols/', verbose_name='تصویر نماد')),
            ],
            options={
                'verbose_name': 'نماد اعتماد',
                'verbose_name_plural': 'نمادهای اعتماد',
            },
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'تصویر گالری', 'verbose_name_plural': 'تصاویر گالری'},
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(default='No Title', max_length=100, verbose_name='عنوان عکس'),
            preserve_default=False,
        ),
    ]
