# Generated by Django 5.1.7 on 2025-08-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_alter_galleryimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="تصویر"),
        ),
    ]
