# Generated by Django 5.2.3 on 2025-10-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_galleryimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان نماد')),
                ('image', models.ImageField(upload_to='trust_symbols/', verbose_name='تصویر نماد')),
            ],
            options={
                'verbose_name': 'نماد اعتماد',
                'verbose_name_plural': 'نمادهای اعتماد',
            },
        ),
    ]
