# Generated by Django 5.2.3 on 2025-10-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_trustsymbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان نماد')),
                ('image', models.ImageField(upload_to='trust_symbols/', verbose_name='تصویر نماد')),
            ],
            options={
                'verbose_name': 'لوگویه سایت ',
                'verbose_name_plural': 'لوگویه سایت ',
            },
        ),
    ]
